import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My YouSi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-6 max-w-sm mx-auto bg-white rounded-xl hover:bg-sky-700 shadow-lg flex items-center space-x-4">
        <div className="text-xl font-medium text-black">Chitchat</div>
        <p className="text-slate-500">You have a new message</p>
      </div>
    </div>
  );
}
